
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: 
      - default-runner
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
      - run: npm install -g bats
      - run: bats -v