name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          ls -A ${{ github.workspace }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -A ${{ github.workspace }}
      - run: |
          cd .github/workflows
          ls -A
  test-update-file:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -A
          cd .github/workflows
          ls -A
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '.github/workflows/test2.yaml'
          propertyPath: 'backend.version'
          value: v1.0.1
          commitChange: true
          updateFile: true
          token: ${secrets.REPO_TOKEN}
      - run: git status